services:
  - type: web
    name: gpt-openbook-app
    env: python
    buildCommand: |
      echo "python-3.10.13" > runtime.txt
      pip install -r requirements.txt
    startCommand: streamlit run app/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
