services:
  - type: web
    name: gpt-openbook-app
    env: python
    buildCommand: pip install openai==1.3.5 && pip install -r requirements.txt
    startCommand: streamlit run app/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
